name = "SimpleTDVP"
uuid = "765d4478-17ce-4b55-8368-9fdb3be10e3c"
authors = ["Xuanzhao Gao <gaoxuanzhao@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
